---
- name: Install dehydrated dependencies
  apt: name={{ dehydrated_dependencies }}

- name: Checkout dehydrated from github
  git:
    repo: "{{ dehydrated_repo_url }}"
    update: "{{ dehydrated_update }}"
    dest: "{{ dehydrated_install_root }}"
    version: "{{ dehydrated_version }}"
  when: install_from_url is not defined

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ dehydrated_install_root}}"
    state: directory
    mode: '0755'
  when: install_from_url is defined

- name: Download dehydrated from url
  get_url:
    url: "{{ install_from_url }}"
    dest: "{{ dehydrated_install_root}}/dehydrated"
    mode: "0755"
    username: "{{ install_from_url_username }}"
    password: "{{ install_from_url_password }}"
  when: install_from_url is defined



- name: Create /etc/dehydrated
  file: dest=/etc/dehydrated state=directory owner=root group=root mode=0700

- name: Create wellknown challenge directory
  file:
    path: "{{ dehydrated_wellknown }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: dehydrated_wellknown is defined

- name: Generate dehydrated config
  template:
    dest: "/etc/dehydrated/{{ dehydrated_config_file }}"
    src: config.j2
    owner: root
    group: root
    mode: 0600

- import_tasks: domain_txt.yml

- import_tasks: hooks.yml

- import_tasks: domain_config.yml

- name: Include dns-01-lexicon.yml
  include_tasks: dns-01-lexicon.yml
  when:
    - dehydrated_use_lexicon

- name: Install cronjob
  cron:
    name: "dehydrated-{{ dehydrated_ca_name }}-renew"
    minute: "{{ 59|random(seed=inventory_hostname) }}"
    hour: "{{ 4|random(seed=inventory_hostname) }}"
    user: root
    job: "{{ dehydrated_install_root }}/dehydrated --cron --config /etc/dehydrated/{{ dehydrated_config_file }} --domains-txt /etc/dehydrated/{{ dehydrated_domains_txt }}"
    cron_file: dehydrated
    state: "{{ 'present' if dehydrated_cronjob else 'absent' }}"

- import_tasks: systemd.yml

- import_tasks: registration.yml

- meta: flush_handlers
